#####################################################
# Test Server Utils by FlorianMichael               #
# https://github.com/FlorianMichael/TestServerUtils #
#####################################################

messages:
  prefix: "&6TestServerUtils"
  not-a-player: "&cYou need to be a player to perform this command!"
  no-permission: "&cYou don't have enough permissions to perform this command!"

commands:
  clear:
    permission: "tsu.clear"
    message: "&aYour inventory has been cleared"
  trash:
    permission: "tsu.trash"
  enchant:
    permission: "tsu.enchant"
  repair:
    permission: "tsu.repair"
    message: "&aThe item in your hand was repaired"
  enderchest:
    permission: "tsu.enderchest"
  workbench:
    permission: "tsu.workbench"
  ptime:
    permission: "tsu.ptime"
    message: "&aYou have changed your own time"
  socialspy:
    permission: "tsu.socialspy"
    added-message: "&aYou can now see the commands from other players"
    removed-message: "&cYou can no longer see the commands from other players"
    format: "&a[%s] &7%s"
  setspawn:
    permission: "tsu.setspawn"
    message: "&aThe spawn point has been set to your current position!"
    spawn-position:
      ==: org.bukkit.Location
      world: world
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
  spawn:
    permission: "tsu.spawn"
    message: "&aYou were teleported to the spawn point"
