name: SpigotCommandUtils
version: 1.7.4
author: FlorianMichael as Jesse
api-version: 1.13
description: Just some spigot based commands for test servers
main: de.florianmichael.spigotcommandutils.SpigotCommandUtils
commands:
  clear:
  trash:
  enchant:
  repair:
  fix:
  workbench:
  wb:
  enderchest:
  echest:
  ec:
  ptime:
  socialspy:
  setspawn:
  spawn:
  fly:
  invsee:
  viewarmor:
  giveall:
